name: brasilibid
version: "1.0.0"
config-version: 2

profile: brasilibid

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  brasilibid:
    staging:
      +materialized: view
      +schema: staging
    mart:
      +materialized: table
      +schema: mart
